deepspeed --include localhost:0 train.py \
    --model_name_or_path '/data/weights/wllama' \
    --data_path '/data/datasets/ptc/instruction_setz.json' \
    --output_dir '/data/weights/ltptc' \
    --num_train_epochs 2 \
    --model_max_length 1548 \
    --per_device_train_batch_size 10 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 100 \
    --save_total_limit 6 \
    --learning_rate 2e-5 \
    --warmup_steps 0 \
    --logging_steps 2 \
    --lr_scheduler_type "cosine" \
    --report_to "wandb" \
    --gradient_checkpointing True \
    --deepspeed configs/deepspeed_config.json \
    --fp16 True
